### ISSUE TITLE
js import not working in mac

### ISSUE THREAD

**Issue by msis-adrian** [coldbox-templates/elixir-vuejs#12]
In resources/assets/js/App.js
when i run import and rebuild, the result doesn't get included into the page.

For example:

`import 'vuetify/dist/vuetify.min.css'`
`import 'material-design-icons-iconfont'`

These do get compiled into /includes/js/app.css

The problem and solution is in the /layouts/main.cfm in this code section

```
<cfscript>
        if ( getCache( "template" ).getOrSet( "vue-styles", function() {
            return fileExists( correctedElixirPath( "js/app.css" ) );
        } ) ) {
            writeOutput( '<link rel="stylesheet" type="text/css" href="#correctedElixirPath( "js/app.css" )#" />' );
        }
    </cfscript>
```
On my mac, **fileExists** will look at a path '/my/directory' and translate it to my root of my HD instead of my webroot. My coworker has the same issue.

Knowing this, if i expand my path to get the absolute path, it works as intended. 

```
 <cfscript>
        if ( getCache( "template" ).getOrSet( "vue-styles", function() {
            return fileExists( expandPath(correctedElixirPath( "js/app.css" ))  );
        	} ) ) {

            writeOutput( '<link rel="stylesheet" type="text/css" href="#correctedElixirPath( "js/app.css" )#" />' );
        }
    </cfscript>
```

I also want to note that there is an import of bootstrap in the App.js (line 1) that appears to work but i think it works because it is being compiled via sass in the webpack.config and not the import.

Perhaps there is a better way and/or maybe its a CF bug...but this worked for me.

My setup:
Mac OS Majave 10.14.4
Lucee 5.2.9+31
Coldbox 5.4.0+932

**Comment by lmajano** [comment]
Thanks, I have fixed all issues!

**Comment by Adrian-Sanchez** [comment]
I just tried this repo from scratch again because i was converting an existing app to use this elixir setup.....I did a fresh git clone and a coldbox install onto an empty folder. npm install & run dev

Problem:
The [Main.cfm](https://github.com/coldbox-templates/elixir-vuejs/blob/master/layouts/Main.cfm) layout still has a problem creating the paths correctly...

My solution was to prefix the paths with the includes folder to get it to work..

In the main layout, for every :
`#html.elixirPath( "css/app.css" )#`
I change it to :
`#html.elixirPath( "includes/css/app.css" )#`

My setup:
Mac OS Majave 10.14.4
Lucee 5.2.9+31
coldbox (5.5.0+958)

**Comment by Adrian-Sanchez** [comment]
Sorry to bother...i redid it just to be sure....and it worked fine...

So apparently there's a certain way to migrate to this repo...i'm not sure what it is yet but i'll keep you posted as soon as i find out.
